spring.application.name=backend

#Database
#PREVIOUS LOCAL DATABASE CONFIG:
# spring.datasource.url=jdbc:postgresql://localhost:5432/#your-database-name
# spring.datasource.username=#your-database-username
# spring.datasource.password=#your-database-password

#RDS
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/snapfind}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

#JPA — auto-creates tables from your Java classes
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

#File upload size limit
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=50MB

#App settings
#PREVIOUS LOCAL UPLOAD DIR:
#app.upload-dir=uploads

app.jwt-secret=${JWT_SECRET:#your-secret-key}
app.jwt-expiry-ms=86400000

#pgvector settings
app.face-similarity-threshold=0.6
app.python-service-url=${PYTHON_SERVICE_URL:http://localhost:8000}

#AWS S3 Storage Settings
aws.region=${AWS_REGION:us-east-1}
aws.access-key-id=${AWS_ACCESS_KEY_ID:}
aws.secret-access-key=${AWS_SECRET_ACCESS_KEY:}
aws.s3.bucket-name=${AWS_S3_BUCKET_NAME:snapfind-photos}

spring.jpa.properties.hibernate.type.preferred_array_jdbc_type=ARRAY
spring.datasource.hikari.connection-init-sql=SELECT 1

