spring.application.name=backend

#Database
spring.datasource.url=jdbc:postgresql://localhost:5432/#your-database-name
spring.datasource.username=#your-database-username
spring.datasource.password=#your-database-password

#JPA — auto-creates tables from your Java classes
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#File upload size limit
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=50MB

#App settings
app.upload-dir=uploads
app.jwt-secret=#your-secret-key
app.jwt-expiry-ms=86400000

#pgvector settings
app.face-similarity-threshold=0.6
app.python-service-url=http://localhost:8000

spring.jpa.properties.hibernate.type.preferred_array_jdbc_type=ARRAY
spring.datasource.hikari.connection-init-sql=SELECT 1
